<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWbRy27a\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWbRy27a/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWbRy27a.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWbRy27a\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerWbRy27a\appAppKernelDevDebugContainer([
    'container.build_hash' => 'WbRy27a',
    'container.build_id' => '0b559d85',
    'container.build_time' => 1723813332,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWbRy27a');
