<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6/1nlWqhoawfwCMWamzp'."\n".'zQMtn4rTJj/zzB18+ptUngejwZTpiF0Vy2J3xkDmex6rxvcFQb1hKVjGQO3apFX9'."\n".'UUbBjHxxihJg9TcHtngoV9JM3ohibM1TOGrGdMbCqi7OAwEYhkhV+uBNpWrwWEGL'."\n".'d+q4kLops0f0U43Ej1xvXlgXX+UTuHNi6f+RhRDTOIut3B+kL4IWt/vvN3qoTs50'."\n".'bGbSccsKuohlL85HkFQzbuaqQRrtgKzJuM4ui/K0ZlCVpMXbxZyJybVolMf81Onh'."\n".'sne8dZAq5eanuDgEOhhsLsuaRzIH3s/82fh0/9o2dIoBUFCd8/NrFQk6Yb43H3SL'."\n".'2wIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
