<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.installer' shared service.

return $this->services['worldlineop.installer'] = new \WorldlineOP\PrestaShop\Installer\Installer(($this->services['worldlineop.module'] ?? $this->load('getWorldlineop_ModuleService.php')), ($this->services['worldlineop.tab.manager'] ?? ($this->services['worldlineop.tab.manager'] = new \WorldlineOP\PrestaShop\Utils\TabManager())), ($this->services['worldlineop.status.manager'] ?? ($this->services['worldlineop.status.manager'] = new \WorldlineOP\PrestaShop\Utils\OrderStatusManager())), ($this->services['worldlineop.settings.account.updater'] ?? $this->load('getWorldlineop_Settings_Account_UpdaterService.php')), ($this->services['worldlineop.settings.advanced_settings.updater'] ?? $this->load('getWorldlineop_Settings_AdvancedSettings_UpdaterService.php')), ($this->services['worldlineop.settings.payment_methods.updater'] ?? $this->load('getWorldlineop_Settings_PaymentMethods_UpdaterService.php')), '8.1.6', ($this->services['worldlineop.logger.factory'] ?? $this->load('getWorldlineop_Logger_FactoryService.php')));
