<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.event.presenter' shared service.

return $this->services['worldlineop.event.presenter'] = new \WorldlineOP\PrestaShop\Presenter\WebhookEventPresenter(($this->services['worldlineop.getpayment.presenter'] ?? $this->load('getWorldlineop_Getpayment_PresenterService.php')), ($this->services['worldlineop.getrefund.presenter'] ?? $this->load('getWorldlineop_Getrefund_PresenterService.php')), ($this->services['worldlineop.logger.factory'] ?? $this->load('getWorldlineop_Logger_FactoryService.php')));
