<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.settings.presenter' shared service.

return $this->services['worldlineop.settings.presenter'] = new \WorldlineOP\PrestaShop\Presenter\ModuleConfigurationPresenter(($this->services['worldlineop.module'] ?? $this->load('getWorldlineop_ModuleService.php')), ($this->services['worldlineop.settings.loader'] ?? $this->load('getWorldlineop_Settings_LoaderService.php')));
