<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.getrefund.presenter' shared service.

return $this->services['worldlineop.getrefund.presenter'] = new \WorldlineOP\PrestaShop\Presenter\GetRefundPresenter(($this->services['worldlineop.module'] ?? $this->load('getWorldlineop_ModuleService.php')), ($this->services['worldlineop.logger.factory'] ?? $this->load('getWorldlineop_Logger_FactoryService.php')));
