<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.sdk.client.factory' shared service.

return $this->services['worldlineop.sdk.client.factory'] = new \WorldlineOP\PrestaShop\Sdk\ClientFactory(($this->services['worldlineop.sdk.communicator'] ?? $this->load('getWorldlineop_Sdk_CommunicatorService.php')), ($this->services['worldlineop.settings.factory'] ?? $this->load('getWorldlineop_Settings_FactoryService.php'))->deserialize(($this->services['worldlineop.settings.serializer'] ?? ($this->services['worldlineop.settings.serializer'] = new \WorldlineOP\PrestaShop\Serializer\SettingsSerializer()))->getSerializer()));
