<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPZtMaNT\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPZtMaNT/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerPZtMaNT.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerPZtMaNT\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerPZtMaNT\appAppKernelProdContainer([
    'container.build_hash' => 'PZtMaNT',
    'container.build_id' => 'c83e5d9c',
    'container.build_time' => 1724253702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPZtMaNT');
