<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\WkDemo\Form\Modifier\ProductFormModifier' shared autowired service.

return $this->services['PrestaShop\\Module\\WkDemo\\Form\\Modifier\\ProductFormModifier'] = new \PrestaShop\Module\WkDemo\Form\Modifier\ProductFormModifier(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['form.form_builder_modifier'] ?? ($this->services['form.form_builder_modifier'] = new \PrestaShopBundle\Form\FormBuilderModifier())));
