<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.processor.transaction' shared service.

return $this->services['worldlineop.processor.transaction'] = new \WorldlineOP\PrestaShop\Processor\TransactionResponseProcessor(($this->services['worldlineop.module'] ?? $this->load('getWorldlineop_ModuleService.php')), ($this->services['worldlineop.logger.factory'] ?? $this->load('getWorldlineop_Logger_FactoryService.php')));
