<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.settings.get_products' shared service.

return $this->services['worldlineop.settings.get_products'] = new \WorldlineOP\PrestaShop\Configuration\Product\GetProductsRequest(($this->services['worldlineop.sdk.client'] ?? $this->load('getWorldlineop_Sdk_ClientService.php')), ($this->services['worldlineop.settings.factory'] ?? $this->load('getWorldlineop_Settings_FactoryService.php'))->deserialize(($this->services['worldlineop.settings.serializer'] ?? ($this->services['worldlineop.settings.serializer'] = new \WorldlineOP\PrestaShop\Serializer\SettingsSerializer()))->getSerializer()), ($this->services['worldlineop.logger.factory'] ?? $this->load('getWorldlineop_Logger_FactoryService.php')));
