<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.sdk.communicator' shared service.

return $this->services['worldlineop.sdk.communicator'] = new \OnlinePayments\Sdk\Communicator(($this->services['worldlineop.sdk.connection'] ?? ($this->services['worldlineop.sdk.connection'] = new \OnlinePayments\Sdk\DefaultConnection())), ($this->services['worldlineop.sdk.communicator_configuration.factory'] ?? $this->load('getWorldlineop_Sdk_CommunicatorConfiguration_FactoryService.php'))->getInstance());
