<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container01vCm5L\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container01vCm5L/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container01vCm5L.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container01vCm5L\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container01vCm5L\appAppKernelProdContainer([
    'container.build_hash' => '01vCm5L',
    'container.build_id' => 'e650c192',
    'container.build_time' => 1724233691,
], __DIR__.\DIRECTORY_SEPARATOR.'Container01vCm5L');
