<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.tab.manager' shared service.

return $this->services['worldlineop.tab.manager'] = new \WorldlineOP\PrestaShop\Utils\TabManager();
