<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.settings.payment_methods.updater' shared service.

return $this->services['worldlineop.settings.payment_methods.updater'] = new \WorldlineOP\PrestaShop\Configuration\Updater\PaymentMethodsSettingsUpdater(($this->services['worldlineop.settings.serializer'] ?? ($this->services['worldlineop.settings.serializer'] = new \WorldlineOP\PrestaShop\Serializer\SettingsSerializer()))->getSerializer(), ($this->services['worldlineop.settings.payment_methods.resolver'] ?? ($this->services['worldlineop.settings.payment_methods.resolver'] = new \WorldlineOP\PrestaShop\OptionsResolver\PaymentMethodsSettingsResolver())), ($this->services['worldlineop.settings.factory'] ?? $this->load('getWorldlineop_Settings_FactoryService.php'))->deserialize(($this->services['worldlineop.settings.serializer'] ?? ($this->services['worldlineop.settings.serializer'] = new \WorldlineOP\PrestaShop\Serializer\SettingsSerializer()))->getSerializer()), ($this->services['worldlineop.settings.payment_methods.validation'] ?? $this->load('getWorldlineop_Settings_PaymentMethods_ValidationService.php')), ($this->services['worldlineop.module'] ?? $this->load('getWorldlineop_ModuleService.php')));
