<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.sdk.connection' shared service.

return $this->services['worldlineop.sdk.connection'] = new \OnlinePayments\Sdk\DefaultConnection();
