<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.getpayment.presenter' shared service.

return $this->services['worldlineop.getpayment.presenter'] = new \WorldlineOP\PrestaShop\Presenter\GetPaymentPresenter(($this->services['worldlineop.module'] ?? $this->load('getWorldlineop_ModuleService.php')), ($this->services['worldlineop.sdk.client.factory'] ?? $this->load('getWorldlineop_Sdk_Client_FactoryService.php')), ($this->services['worldlineop.settings.loader'] ?? $this->load('getWorldlineop_Settings_LoaderService.php')), ($this->services['worldlineop.logger.factory'] ?? $this->load('getWorldlineop_Logger_FactoryService.php')));
