<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'worldlineop.settings.payment_methods.validation' shared service.

return $this->services['worldlineop.settings.payment_methods.validation'] = new \WorldlineOP\PrestaShop\Configuration\Validation\PaymentMethodsValidationData(($this->services['worldlineop.module'] ?? $this->load('getWorldlineop_ModuleService.php')));
