services:
  PrestaShop\Module\AsGroup\Form\Modifier\ProductFormModifier:
    autowire: true
    public: true
    arguments:
      $formBuilderModifier: '@form.form_builder_modifier'


  form.type.sell.product.seo.seo_type.custom:
    class: 'PrestaShop\Module\AsGroup\Form\Admin\Sell\Product\SEO\SEOType'
    decorates: form.type.sell.product.seo.seo_type
    decoration_inner_name: form.type.sell.product.seo.seo_type.inner
    public: true
    arguments:
      - '@translator'
      - "@router"
      - "@=service('prestashop.adapter.legacy.configuration').getBoolean('PS_REWRITING_SETTINGS')"
      - "@=service('prestashop.adapter.legacy.configuration').getBoolean('PS_FORCE_FRIENDLY_PRODUCT')"
      - '@prestashop.adapter.legacy.context'
      - '@PrestaShop\PrestaShop\Core\ConfigurationInterface'
      - '@form.type.sell.product.seo.seo_type.inner'
    tags:
      - { name: form.type }
  

  
  form.type.sell.product.combination_item_type.custom:
    class: PrestaShop\Module\AsGroup\Form\Admin\Sell\Product\Combination\CombinationItemType
    decorates: form.type.sell.product.combination_item_type  # Decorate the core service
    decoration_inner_name: form.type.sell.product.combination_item_type.inner
    arguments:
      - '@translator'
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"
      - '@=service("prestashop.adapter.data_provider.currency").getDefaultCurrency()'
      - '@prestashop.adapter.feature.multistore'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'
      - '@form.type.sell.product.combination_item_type.inner'  # Reference to the original service if needed
    public: true
    tags:
      - { name: form.type }

  PrestaShop\Module\AsGroup\Adapter\Product\Update\ProductDuplicator:
    autowire: true
    public: true
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $productImageSystemPathFactory: '@prestashop.adapter.product.image.product_image_filesystem_path_factory'
      $productRepository: '@prestashop.adapter.product.repository'
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $translator: '@translator'
      $stringModifier: '@prestashop.core.string.string_modifier'
      $combinationRepository: '@prestashop.adapter.combination.repository'
      $productSupplierRepository: '@prestashop.adapter.product.supplier.repository'
      $specificPriceRepository: '@prestashop.adapter.specific_price.repository'
      $stockAvailableRepository: '@prestashop.adapter.stock_available.repository'
      $productStockUpdater: '@prestashop.adapter.product.stock.updater'
      $combinationStockUpdater: '@prestashop.adapter.combination.stock.updater'
      $productImageRepository: '@prestashop.adapter.product.image.repository'

  # This makes PrestaShop use your duplicator in place of the default one
  PrestaShop\PrestaShop\Adapter\Product\Update\ProductDuplicator:
    alias: PrestaShop\Module\AsGroup\Adapter\Product\Update\ProductDuplicator
    public: true



  prestashop.adapter.order.refund.order_slip_creator:
    class: PrestaShop\Module\AsGroup\OrderSlipCreator
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@translator'

  # PrestaShop\Module\AsGroup\Controller\Admin\OrderController:
  #   autowire: true
  #   public: true
  #   tags:
  #     - { name: 'controller.service_arguments' }
  #   arguments:
  prestashop.adapter.product.repository:
    alias: PrestaShop\PrestaShop\Adapter\Product\Repository\ProductRepository
    public: true

  PrestaShop\Module\AsGroup\Controller\Admin\ProductController:
    public: true
    arguments:
      - '@prestashop.adapter.product.repository'
